### ISSUE TITLE
On-caller Onboarding Checklist - @thorrsson

### ISSUE THREAD

**Issue by thorrsson** [thorrsson/github-maven-package-example#14]
This issue serves as a guide to help prepare on-callers who will lead incidents. The services listed on https://githubstatus.com represent our most critical customer facing services. On-callers who work on these services are required to be trained in Incident Management.

The checklist below highlights the most important learning objectives of the Incident Management training. As you complete the training, please check off the items you feel comfortable with. SRE will review this checklist to track each team's progress. This data will be aggregated into each service's Incident Management Training scorecard.

## Checklist
- [ ] I participated in an [Incident Management Training Workshop](https://docs.google.com/presentation/d/1HRqHVBrXoq6RoA-3RWJJ2_r8efteOvzI2ycW7CI3UIA/edit?usp=sharing) (either live or by reviewing a recording). (`oncaller_completed_workshop?`)
- [ ] I participated in an Incident Management Game Day Exercise (either live or by reviewing a recording). (`oncaller_completed_gameday?`)
- [ ] I confirmed my PagerDuty account is [configured correctly](https://github.com/github/on-call/blob/master/docs/before/sme_pagerduty.md) using the `.pager-lint` ChatOp. (`oncaller_configured_pagerduty?`)
- [ ] I know [how to use](https://github.com/github/status/blob/c02ae477c40402b2ea0ce613341bc61ecd7dcc01/README.md) the `.status` and `.pager` ChatOps. (`oncaller_knows_tooling?`)
- [ ] I know [how to assess](https://docs.google.com/presentation/d/1HRqHVBrXoq6RoA-3RWJJ2_r8efteOvzI2ycW7CI3UIA/edit#slide=id.g8c561b96cf_0_27) the customer impact of an incident involving my service. (`oncaller_knows_customer_impact?`)
- [ ] I know the dependencies of my service, and know how to page the responsible team if something breaks. (`oncaller_knows_dependencies?`)
- [ ] I know the Incident Management [roles and responsibilities](https://github.com/github/on-call/blob/master/docs/before/roles.md), and know how to perform them. (`oncaller_knows_roles?`)
- [ ] I am ready to lead an incident. (`oncaller_acks_ready?`)

## Training Resources
- Incident Management Workshop - [Slide Deck](https://docs.google.com/presentation/d/1HRqHVBrXoq6RoA-3RWJJ2_r8efteOvzI2ycW7CI3UIA/edit?usp=sharing)
- [github/on-call](https://github.com/github/on-call) - A guide on Incident Response at GitHub.

## Getting Help
- If you have questions on any of the training materials, or would like to schedule 1:1 time to ask questions, please reach out to #sre in Slack.
